version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: root
      POSTGRES_PASSWORD: esgi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
